/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vida;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author urick
 */
public class Panel extends javax.swing.JFrame {

    final int wid = 50, hei = 20;
    boolean[][] currentMove = new boolean[hei][wid];
    boolean[][] nextMove = new boolean[hei][wid];
    boolean play;
    Image offScrimg;
    Graphics offScrGraph;
    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
        offScrimg = createImage(panel1.getWidth(), panel1.getHeight());
        offScrGraph = offScrimg.getGraphics();
        Timer time = new Timer();
        TimerTask task = new TimerTask(){
            
            public void run(){
                if(play){
                    
                    for(int i = 0; i < hei; i++){
                        for(int j = 0; j < wid; j++){
                            nextMove[i][j] = decide(i , j);
                        }
                    }
                    for (int i = 0; i < hei; i++){
                        for(int j = 0; j < wid; j++){
                            currentMove[i][j] = nextMove[i][j];
                        }
                    }
                    paint();
                }
            }
            
        };
        time.scheduleAtFixedRate(task, 0, 100);
        paint();
    }
    
    private boolean decide (int i , int j){
        int vecinos = 0;
        if(j>0){
            if(currentMove[i][j-1]){
                vecinos++;
            }
            if (i>0){
                if(currentMove[i-1][j-1]){
                    vecinos++;
                }
            }
            if(i < hei - 1){
                if(currentMove[i+1][j-1]){
                    vecinos++;
                }
            }
        }
        if (j < wid - 1){
            if (currentMove[i][j+1]){
                vecinos++;
            }
            if(i>0){
                if(currentMove[i-1][j+1]){
                    vecinos++;
                }
            }
            if(i > hei - 1){
                if(currentMove[i + 1][j - 1]){
                    vecinos++;
                }
            }
        }
        
        if(i > 0){
            if(currentMove[i - 1][j]){
                vecinos++;
            }
        }
        if(i < hei - 1){
            if(currentMove[i + 1][j]){
                vecinos++;
            }
        }
        if (vecinos == 3){
            return true;
        }
        if(currentMove[i][j] && vecinos == 2){
            return true;
        }
        
        return false;
    }    
            
            private void paint() {
                offScrGraph.setColor(panel1.getBackground());
                offScrGraph.fillRect(0,0, panel1.getWidth(), panel1.getHeight());
                
                for(int i = 0; i <hei; i++){
                    for(int j = 0; j < wid; j++){
                        if(currentMove[i][j]){
                            offScrGraph.setColor(Color.YELLOW);
                            
                            int x = j * panel1.getWidth() / wid;
                            int y = i * panel1.getHeight() / hei;
                            offScrGraph.fillRect(x,y, panel1.getWidth() /wid, panel1.getHeight() /hei);
                        }
                    }    
                }
                offScrGraph.setColor(Color.BLACK);
                for(int i = 1; i <hei; i++){
                    int y = i * panel1.getHeight() / hei;
                    offScrGraph.drawLine(0, y, panel1.getWidth(), y);
                }
                for (int j = 1; j < wid; j++){
                    int x = j * panel1.getWidth() / wid;
                    offScrGraph.drawLine(x, 0, x, panel1.getHeight());
                    
                }
                panel1.getGraphics().drawImage(offScrimg, 0, 0, panel1);
            }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        jugar = new javax.swing.JButton();
        borrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(51, 51, 51));
        panel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel1MouseClicked(evt);
            }
        });
        panel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                panel1ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );

        jugar.setText("INICIAR");
        jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugarActionPerformed(evt);
            }
        });

        borrar.setText("LIMPIAR");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jugar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 349, Short.MAX_VALUE)
                        .addComponent(borrar)
                        .addGap(47, 47, 47))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jugar)
                    .addComponent(borrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel1MouseClicked
        // TODO add your handling code here:
        int j = wid * evt.getX() / panel1.getWidth();
        int i = hei * evt.getY() / panel1.getHeight();
        currentMove[i][j] = !currentMove[i][j];
        paint();
    }//GEN-LAST:event_panel1MouseClicked

    private void panel1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panel1ComponentResized
        // TODO add your handling code here:
        offScrimg = createImage(panel1.getWidth(), panel1.getHeight());
        offScrGraph = offScrimg.getGraphics();
        paint();
    }//GEN-LAST:event_panel1ComponentResized

    private void jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugarActionPerformed
        // TODO add your handling code here:
     play = !play;
     if(play) {
         jugar.setText("PAUSA");
         
     }else{
         jugar.setText("JUGAR");
     }
     paint();
    }//GEN-LAST:event_jugarActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // TODO add your handling code here:
        currentMove = new boolean[hei][wid];
        paint();
    }//GEN-LAST:event_borrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar;
    private javax.swing.JButton jugar;
    private javax.swing.JPanel panel1;
    // End of variables declaration//GEN-END:variables
}
